# Generated by Django 5.2.7 on 2025-12-10 08:47

import django.db.models.deletion
import tenants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, help_text='National ID or identification number', max_length=50, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, help_text="Tenant's occupation or job", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant profile is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when tenant profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when tenant profile was last updated')),
                ('user', models.OneToOneField(help_text='User account associated with this tenant profile', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Profile',
                'verbose_name_plural': 'Tenant Profiles',
                'db_table': 'tenant_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.CharField(default=tenants.models.generate_assignment_id, editable=False, help_text='Unique assignment identifier (ASN-XXX format)', max_length=20, primary_key=True, serialize=False)),
                ('move_in_date', models.DateField(help_text='Date when tenant moved into the room')),
                ('lease_end_date', models.DateField(blank=True, help_text='Expected lease end date (can be extended)', null=True)),
                ('move_out_date', models.DateField(blank=True, help_text='Actual date when tenant moved out (null if still occupying)', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current active assignment')),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text="Monthly rent amount (can differ from room's base price)", max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when assignment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when assignment was last updated')),
                ('room', models.ForeignKey(help_text='Room being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rooms.room')),
                ('tenant', models.ForeignKey(help_text='Tenant assigned to the room', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.tenantprofile')),
            ],
            options={
                'verbose_name': 'Room Assignment',
                'verbose_name_plural': 'Room Assignments',
                'db_table': 'room_assignments',
                'ordering': ['-move_in_date'],
                'indexes': [models.Index(fields=['tenant', 'is_current'], name='room_assign_tenant__3913bc_idx'), models.Index(fields=['room', 'is_current'], name='room_assign_room_id_deb5fe_idx')],
            },
        ),
    ]
