# Generated by Django 5.2.7 on 2025-11-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Unique room identifier (e.g., A101, B205)', max_length=20, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('shared', 'Shared')], help_text='Type of room: single, double, or shared', max_length=20)),
                ('floor', models.IntegerField(help_text='Floor number where the room is located')),
                ('capacity', models.IntegerField(help_text='Maximum number of occupants allowed')),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly rent price', max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', help_text='Current status of the room', max_length=20)),
                ('facilities', models.TextField(blank=True, help_text='List of facilities/amenities (e.g., AC, WiFi, Bathroom)')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes about the room')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when room was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when room was last updated')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['room_number'],
            },
        ),
    ]
