# Generated by Django 5.2.7 on 2025-12-10 08:47

import complaints.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.CharField(default=complaints.models.generate_complaint_id, editable=False, help_text='Unique complaint identifier (CPL-XXX format)', max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief description of the complaint', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('category', models.CharField(choices=[('maintenance', 'Pemeliharaan/Perbaikan'), ('facilities', 'Fasilitas'), ('cleanliness', 'Kebersihan'), ('noise', 'Kebisingan'), ('security', 'Keamanan'), ('other', 'Lainnya')], default='other', help_text='Type of complaint', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('urgent', 'Mendesak')], default='medium', help_text='Priority level of this complaint', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Baru'), ('in_progress', 'Dalam Proses'), ('resolved', 'Selesai'), ('closed', 'Ditutup')], default='open', help_text='Current status of complaint', max_length=20)),
                ('attachment', models.ImageField(blank=True, help_text='Photo evidence of the issue (optional)', null=True, upload_to='complaint_attachments/%Y/%m/')),
                ('resolution_notes', models.TextField(blank=True, help_text='Admin notes on how complaint was resolved', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When complaint was marked as resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When complaint was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved the complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, help_text='Room this complaint is about (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='rooms.room')),
                ('tenant', models.ForeignKey(help_text='Tenant who submitted this complaint', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='tenants.tenantprofile')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.CharField(default=complaints.models.generate_comment_id, editable=False, help_text='Unique comment identifier (CMT-XXX format)', max_length=20, primary_key=True, serialize=False)),
                ('comment', models.TextField(help_text='Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When comment was posted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last edit timestamp')),
                ('complaint', models.ForeignKey(help_text='Complaint this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='complaints.complaint')),
                ('user', models.ForeignKey(help_text='User who posted this comment', on_delete=django.db.models.deletion.CASCADE, related_name='complaint_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Comment',
                'verbose_name_plural': 'Complaint Comments',
                'db_table': 'complaint_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['tenant', 'status'], name='complaints_tenant__5221a1_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'priority'], name='complaints_status_285d57_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['category', 'status'], name='complaints_categor_5f44a3_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='complaints_created_a37218_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcomment',
            index=models.Index(fields=['complaint', 'created_at'], name='complaint_c_complai_bbf7b9_idx'),
        ),
    ]
