# Generated by Django 5.2.7 on 2025-11-12 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_period_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month this payment is for (1-12)')),
                ('payment_period_year', models.IntegerField(help_text='Year this payment is for (e.g., 2025)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount (usually monthly_rent from assignment)', max_digits=12)),
                ('due_date', models.DateField(help_text='Date payment is due (e.g., 5th of month)')),
                ('payment_date', models.DateField(blank=True, help_text='Actual date payment was received (null if not paid)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('other', 'Other')], help_text='Method of payment', max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Transfer reference number or receipt number', max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, default='Bank BCA', help_text='Bank name if payment by transfer', max_length=100, null=True)),
                ('bank_account_name', models.CharField(blank=True, default='Rahman Hadi', help_text='Bank account holder name', max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number for transfers', max_length=50, null=True)),
                ('proof_of_payment', models.FileField(blank=True, help_text='Receipt or proof of payment image/PDF', null=True, upload_to='payment_proofs/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this payment record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when marked as paid', null=True)),
                ('assignment', models.ForeignKey(blank=True, help_text='Room assignment this payment is for (may be null if assignment deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tenants.roomassignment')),
                ('paid_by', models.ForeignKey(blank=True, help_text='Admin who marked payment as paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant making this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenantprofile')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_period_year', '-payment_period_month', '-due_date'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='payments_tenant__c38e7b_idx'), models.Index(fields=['status', 'due_date'], name='payments_status_422e56_idx'), models.Index(fields=['payment_period_year', 'payment_period_month'], name='payments_payment_cc75ef_idx'), models.Index(fields=['due_date'], name='payments_due_dat_ff319d_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'payment_period_month', 'payment_period_year'), name='unique_payment_per_period')],
            },
        ),
    ]
